apiVersion: apps/v1
kind: Deployment
metadata:
  name: hilltop-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: ndahtems/nodeapp-app:latest
        ports:
        - containerPort: 8080
