apiVersion: apps/v1
kind: Deployment
metadata:
  name: hilltop-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: chafah/hilltop-nodejs-app:new
        ports:
        - containerPort: 8080
